### ISSUE TITLE
Emulate BLE peripheral device button press

### ISSUE THREAD

**Issue by and7ey** [sandeepmistry/osx-ble-peripheral#3]
Could you please update your code by adding an example like when user pressed any button on BLE peripheral device? Thanks in advance.

**Comment by sandeepmistry** [comment]
@and7ey I'd be happy to merge a pull request for this in.

It's pretty low on my priority list as of now though.

**Comment by sandeepmistry** [comment]
Closing for now, not likely going to happen unless someone provides a pull request.
